spring.application.name=StudentManagementSystemEpicdemo

spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=Bavindu@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

logging.level.org.springframework.jdbc.core=DEBUG

# Generate log file
logging.file.name=logs/student-system.log

# Optional log level
logging.level.root=INFO